#!/bin/sh
# system one time tasks

export PATH=/bin

mount -t proc proc /proc
mount -o remount,rw /
mount -t sysfs sys /sys
mkdir -p /dev/pts
mount -t devpts devpts /dev/pts
echo /bin/mdev > /proc/sys/kernel/hotplug
hostname $(cat /etc/hostname)
cat /proc/mounts > /etc/mtab

touch /etc/runit/stopit
chmod 0 /etc/runit/stopit

cd /
