#!/bin/ash

if [ ${#2} -gt 0 ]; then
	if [ "z$1" = "zenable" ]; then
		if [ -d "/service/enabled/"$2 ]; then
			if [ "z$3" != 'zquiet' ]; then
				echo The service is already enabled!
			fi
		else
			ln -s /service/$2 /service/enabled/$2
			if [ "z$3" != 'zquiet' ]; then
				echo [+] $i
			fi
		fi
	elif [ "z$1" = "zdisable" ]; then
		if [ -d "/service/enabled/"$2 ]; then
			rm /service/enabled/$2
			if [ "z$3" != 'zquiet' ]; then
				echo [-] $i
			fi
		else
			if [ "z$3" != 'zquiet' ]; then
				echo The service is already disabled!
			fi
		fi
	fi
elif [ "z$1" = "zlist" ]; then
	for i in $(ls /service); do
		if [ $i != "enabled" ]; then
			if [ -d "/service/enabled/"$i ]; then
				echo [+] $i
			else
				echo [-] $i
			fi
		fi
	done
else
	echo "svctl <enable|disable|list> [service]"
fi
