#!/bin/mksh

if [ ${#2} -gt 0 ]; then
	if [ "z$1" = "zdisable" ]; then
		if [ -d "/service/"$2 ]; then
			if [ -f "/service/"$2"/down" ]; then
				if [ "z$3" != 'zquiet' ]; then
					echo The service is already disabled!
				fi
			else
				touch "/service/"$2"/down"
				if [ "z$3" != 'zquiet' ]; then
					echo "[-] $2"
				fi
			fi
		else
			echo This service does not exist!
		fi
	elif [ "z$1" = "zenable" ]; then
		if [ -d "/service/"$2 ]; then
			if [ -f "/service/"$2"/down" ]; then
				rm /service/$2/down
				if [ "z$3" != 'zquiet' ]; then
					echo "[+] $2"
				fi
			else
				if [ "z$3" != 'zquiet' ]; then
					echo The service is already enabled!
				fi
			fi
		else
			echo This service does not exist!
		fi
	fi
elif [ "z$1" = "zlist" ]; then
	for i in $(ls /service); do
		if [ -f "/service/"$i"/down" ]; then
			echo [-] $i
		else
			echo [+] $i
		fi
	done
else
	echo "svctl <enable|disable|list> [service]"
fi
